-- Deploy spottrek:master.playout to pg

BEGIN;

create table master.playout (
	  broadcastercode integer,
	  contenttypecode integer,
	  channelcode integer,
	  title text,
	  titlecode integer,
	  contentlanguagecode integer,
	  telecastdate date,
	  telecastday text,
	  telecaststarttime time,
	  telecastendtime time,
	  telecastduration time,
	  descriptorcode integer,
	  breaknumber integer,
	  positioninbreak integer,
	  countinbreak integer,
	  durationinbreak text, -- not sure of data type
	  breakduration text, -- not sure of data type
	  countperprogram integer,
	  durationperprogram text, -- not sure of data type
	  totalbreakcountperprogram integer,
	  totalbreakdurationperprogram integer,
	  promotypecode integer,
	  promocategorycode integer,
	  promochannelcode integer,
	  promosponsorname text,
	  promoprogramnamecode integer,
	  promoprogramthemecode integer,
	  promoprogramgenrecode integer,
	  programthemecode integer,
	  programgenrecode integer,
	  programsegmentnumber integer,
	  numberofsegmentsinprogram integer,
	  productservicenamecode integer,
	  brandnamecode integer,
	  subbrandnamecode integer,
	  advertisercode integer,
	  commercialprogramnamecode integer,
	  commercialprogramthemecode integer,
	  commercialprogramgenrecode integer,
	  sport text,
	  originalorrepeat text,
	  live text,
	  combinedpositioninbreak integer,
	  combinedcountinbreak integer,
	  promoprogramstarttime time,
	  commercialprogramstarttime time,
	  spotid bigint,
	  lastmodifieddate date,
	  adbreakcode text,
	  promobroadcastercode integer,
	  beam text,
	  split text,
	  market text,
	  splitregion text,
	  splitplatform text,
	  prodhouse text,
	  created_on timestamp default current_timestamp,
	  primary key (spotid),
	  foreign key (contenttypecode) references master.contenttype (contenttypecode),
	  foreign key (channelcode) references master.channel (channelcode),
	  foreign key (contentlanguagecode) references master.contentlanguage (contentlanguagecode),
	  foreign key (descriptorcode) references master.descriptor (descriptorcode),
	  foreign key (programthemecode) references master.programtheme (programthemecode),
	  foreign key (programgenrecode) references master.programgenre (programgenrecode),
	  foreign key (brandnamecode) references master.brand (brandnamecode),
	  foreign key (advertisercode) references master.advertiser (advertisercode)
);

COMMIT;
